[package]
name = "clipboard_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
arboard = "3.4.1"
# clipboard = "0.5.0"
# wl-clipboard-rs = "0.9.1"
